### ISSUE TITLE
No way to deal with top-level arrays

### ISSUE THREAD

**Issue by treyharris** [jonathanstowe/JSON-Class#2]
Please see the gist at https://gist.github.com/treyharris/7b57dd3855d3afb9461d86c13938362f

I'm using JSON::Infer, but the issue originates with JSON::Class. There's no way for me to parse this file. Perhaps something as simple as

```
my Something @something = Something.from-json($contents);
```

?

**Comment by jonathanstowe** [comment]
It's actually JSON::Unmarshal that needs to altered,  everything is in there to do it, it just needs to know that the data is an array of the objects it wants to unmarshal not a single one.

**Comment by jonathanstowe** [comment]
Hi,
I've just done some better testing and actually discovered that JSON::Unmarshal doesn't need to be changed, it's just the other bits need to be able to deal with the Array case.  That is if you tell it you want a an Array[Object] it does the right thing, however JSON::Class won't like that because the array  returned won't be a JSON::Class, so I'm going to fix that (easy) and then fix JSON::Infer to generate some code like :

```
package Homebrew {
    our constant Formulas = (Array[Homebrew::Formula] but JSON::Class);
}
```

And it'll all be good.  I'll make the change to JSON::Class first so you can actually use the above rather than my original workaround, then do the actual generating of the above in JSON::Infer if the input data is an array.

**Comment by jonathanstowe** [comment]
I've just update JSON::Class to be able to deal with this nicely, so next time you update it should work as above.  If you want to serialise the same objects then you will also need to update JSON::Marshal
