### ISSUE TITLE
Invitation to participate in the Squashathon + Hacktoberfest.

### ISSUE THREAD

**Issue by JJ** [jonathanstowe/JSON-Class#7]
For the time being, this is the non-core distribution with the highest accumulated number of dependencies, according to [River](https://github.com/JJ/p6-river/blob/master/data/river-scores.csv). It would be great if you added it to the [Squashathon](https://github.com/perl6/ecosystem/wiki/SQUASHathon#participating-repos)

**Comment by jonathanstowe** [comment]
Well the module itself doesn't really have much scope itself for having bugs ;-)  It entirely depends on JSON::Marshal and JSON::Unmarshal, the only open issues are because I haven't closed them yet.

I think it's in the position it is in the dependencies chart because I've used it in a third of my modules :-)
